# Generated by Django 4.0.4 on 2022-05-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_dateend_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateStart',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
