# Generated by Django 4.0.4 on 2022-05-05 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_datestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stockStart',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
