# Generated by Django 4.0.4 on 2022-05-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_stockstart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='priceCurrent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='priceEnd',
        ),
    ]
